export default {
  namespaced: true,

  state: {
    firstColumn: [
      {
        title: "Html",
        link: "/recruitment-questions/htmlquestions",
        bookLink: '/book/html',
        icon: "mdi-language-html5",
        color: "orange",
      },
      {
        title: "Css",
        link: "/recruitment-questions/cssquestions",
        bookLink: '/book/css',
        icon: "mdi-language-css3",
        color: "blue",
      },
      {
        title: "Javascript",
        link: "/recruitment-questions/javascript",
        bookLink: '/book/javascript',
        icon: "mdi-language-javascript",
        color: "yellow",
      },
      {
        title: "Vue",
        link: "/recruitment-questions/vue",
        bookLink: '/book/vue',
        icon: "mdi-vuejs",
        color: "green",
      },
      {
        title: "React",
        link: "/recruitment-questions/react",
        bookLink: '/book/react',
        icon: "mdi-react",
        color: "blue",
      },
      {
        title: "Typescript",
        link: "/recruitment-questions/typescript",
        bookLink: '/book/typescript',
        icon: "mdi-language-typescript",
        color: "blue",
      },
      {
        title: "Git",
        link: "/recruitment-questions/gitquestions",
        bookLink: '/book/git',
        icon: "mdi-git",
        color: "black",
      },
      {
        title: "Ogólne",
        link: "/recruitment-questions/general",
        bookLink: '/book/general',
        icon: "mdi-account-circle",
        color: "red",
      },
      {
        title: "Testowanie",
        link: "/recruitment-questions/test",
        bookLink: '/book/tests',
        icon: "mdi-wrench-outline",
        color: "grey",
      },
      {
        title: "Cypress",
        link: "/recruitment-questions/cypress",
        icon: "mdi-test-tube",
        color: "green",
      },
      {
        title: "Postman",
        link: "/recruitment-questions/postman",
        icon: "mdi-post-outline",
        color: "orange",
      },
      {
        title: "Sql",
        link: "/recruitment-questions/sql",
        icon: "mdi-database-search",
        color: "black",
      },
      {
        title: "Wordpress",
        link: "/recruitment-questions/wordpress",
        icon: "mdi-wordpress",
        color: "lightblue",
      },
      {
        title: "Cybersecurity",
        link: "/recruitment-questions/cybersecurity",
        icon: "mdi-lock",
        color: "blue",
      },
      {
        title: "Cloud",
        link: "/recruitment-questions/cloud",
        icon: "mdi-lock",
        color: "blue",
      },
    ],
  },
};
