export default {
  namespaced: true,

  state: {
    firstColumn: [
      {
        title: "Html",
        link: "/recruitment-questions/htmlquestions",
        bookLink: '/book/html',
        icon: "mdi-language-html5",
        color: "orange",
        id: 1,
      },
      {
        title: "Css",
        link: "/recruitment-questions/cssquestions",
        bookLink: '/book/css',
        icon: "mdi-language-css3",
        color: "blue",
        id: 2,
      },
      {
        title: "Javascript",
        link: "/recruitment-questions/javascript",
        bookLink: '/book/javascript',
        icon: "mdi-language-javascript",
        color: "yellow",
        id: 3,
      },
      {
        title: "Vue",
        link: "/recruitment-questions/vue",
        bookLink: '/book/vue',
        icon: "mdi-vuejs",
        color: "green",
        id: 4,
      },
      {
        title: "React",
        link: "/recruitment-questions/react",
        bookLink: '/book/react',
        icon: "mdi-react",
        color: "blue",
        id: 5,
      },
      {
        title: "Typescript",
        link: "/recruitment-questions/typescript",
        bookLink: '/book/typescript',
        icon: "mdi-language-typescript",
        color: "blue",
        id: 6,
      },
      {
        title: "Git",
        link: "/recruitment-questions/gitquestions",
        bookLink: '/book/git',
        icon: "mdi-git",
        color: "black",
        id: 7,
      },
      {
        title: "Ogólne",
        link: "/recruitment-questions/general",
        bookLink: '/book/general',
        icon: "mdi-account-circle",
        color: "white",
        id: 8,
      },
      {
        title: "Testowanie",
        link: "/recruitment-questions/test",
        bookLink: '/book/tests',
        icon: "mdi-wrench-outline",
        color: "grey",
        id: 9,
      },
    ],
  },
};
